# -*- coding: utf-8 -*-
"""Image Recognition System using Deep Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4i6bl-rTYlVGmOPdmunOiicWgxZpeIF

## Deep Learning: Group Assignment

**1. Import all nescessly libraries**

* **TensorFlow**: TensorFlow is a library designed to efficiently perform model training by constructing computation graphs and performing automatic differentiation. During the forward pass, TensorFlow records all operations onto a “tape.” Once the loss is computed, TensorFlow plays this tape backward to automatically and efficiently calculate gradients based on the chain rule. Internally, TensorFlow builds a graph where each computation is represented as a “node” and the flow of tensors is represented as an “edge.”

* **Keras**: Keras uses TensorFlow as its internal computation engine and provides an easy and intuitive interface for building neural networks. This allows users to write models using Keras’s simple syntax while leveraging TensorFlow’s powerful computation engine under the hood.

(Other libraries)

* **os, io, pathlib**: Libraries for interacting with the computer's file system, such as reading and writing files and handling paths.

* **PIL**: A library for handling images. It is used for loading, resizing, rotating, and color correction of images.

* **numpy**: A library for treating images as matrices (arrays) of pixel values and performing calculations on them.

* **matplotlib.pyplot, seaborn**: Libraries for visually displaying data and model training results in an easy-to-understand way, typically through graphs and plots.

* **cv2**: A library for computer vision.

* **sklearn.metrics**: A library for checking evaluation metrics of a model, such as accuracy, recall, and F1 score.
"""

# Standard Libraries
import os # For OS functionalities like path manipulation and directory creation
import io # For handling in-memory binary data (like images)
import random # For introducing randomness (e.g., shuffling, augmentations)
from pathlib import Path # For object-oriented filesystem path operations
import PIL
from PIL import Image, ImageChops, ImageEnhance, UnidentifiedImageError # PIL: For loading, processing, and handling image errors

# Data Science & Numerical Calculation
import numpy as np # For numerical calculations
import pandas as pd # For handling data structures (like DataFrames, CSVs)

# For Data Visualization (Graphs, Images)
import matplotlib.pyplot as plt
import seaborn as sns

# For Image Processing
import cv2

# Model Evaluation
from sklearn.metrics import classification_report # For detailed model evaluation (precision, recall, F1-score)

# TensorFlow / Keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import regularizers # To apply regularization (e.g., L2) to layers to prevent overfitting
from tensorflow.keras.models import Model
from tensorflow.keras.applications import ResNet50 # To load the pre-trained ResNet50 model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout # Layers to add to the model (Dense, Pooling, Dropout)
from tensorflow.keras.preprocessing.image import ImageDataGenerator # For automatic image data loading and data augmentation
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.optimizers import Adam # Adam optimization algorithm for model training
# ↓ Callbacks for early stopping, model saving, and dynamic LR adjustment
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

from google.colab import drive
drive.mount('/content/drive')

"""Download helper functions from an external source for tasks such as recording training progress, visualizing the Loss Curve, and accessing files within a folder."""

# Download & Import Helper function from website
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

from helper_functions import create_tensorboard_callback, walk_through_dir, make_confusion_matrix

"""**2: Download ziped data for train & test and unzip it on local google colab**

To reduce the execution time in Colab, we will first copy the data from Google Drive to the local Colab environment. Directly reading files from Google Drive is very slow due to network latency, which results in long execution times. This time, we will only copy the zip file from Google Drive to the Colab local disk once at the beginning of the notebook, and then unzip and use it there.
"""

print("--- Copying zip file from Google Drive to local... ---")

# Copy the zip file from Google Drive to the local disk '/content/' on Colab
!cp /content/drive/MyDrive/Deep_Learning_Group_Assignment.zip /content/
print("--- Copy complete. Unzipping the file on local ---")

!unzip -q /content/Deep_Learning_Group_Assignment.zip -d /content/
print("--- Unzipping complete. The dataset is ready at '/content/Deep_Learning_Group_Assignment.zip'. ---")


# Path Settings
LOCAL_DATASET_PATH = "/content/Deep_Learning_Group_Assignment"
train_dir = os.path.join(LOCAL_DATASET_PATH, "train/")
test_dir = os.path.join(LOCAL_DATASET_PATH, "test/")

print(f"Train directory: {train_dir} (Exists: {os.path.exists(train_dir)})")
print(f"Test directory: {test_dir} (Exists: {os.path.exists(test_dir)})")

"""**3: Fix seeds for Python, NumPy, and TensorFlow to ensure the reproducibility of experiments**

Fixing the random seed ensures that random operations, such as weight initialization and data shuffling, produce the same results every time. This achieves high reproducibility.
"""

def seed_everything(seed=42):

    # Set the seed for Python, NumPy, and TensorFlow
    tf.random.set_seed(seed)
    np.random.seed(seed)
    random.seed(seed)

    # Disable hash randomization for Python
    os.environ['PYTHONHASHSEED'] = str(seed)
    tf.config.experimental.enable_op_determinism()

seed_everything()
print("Seeds have been fixed. The reproducibility of the experiment is ensured")

"""**4:  Set basic model parameters & Check the data directory**

Set the batch size to 32 and the target size to 224, 224. Also, check the number of files in each directory.
"""

# Settings

# Basic model parameters
BATCH_SIZE = 32
TARGET_SIZE = (224, 224)

# Check the directory structure
print("--- Training data directory structure ---")
walk_through_dir(train_dir)
print("\n--- Test data directory structure ---")
walk_through_dir(test_dir)

"""**5: Deffine DataFrame against all image path and crrect label**

Recursively search for image file paths with various extensions and extract the class label, which is the parent directory name, from the file paths. Based on this, create separate DataFrames for the training and test sets, and display the number of data points (images) in each. This will confirm that the data has been loaded correctly.
"""

def convert_path_to_df(directory):

    image_dir = Path(directory)

    filepaths = list(image_dir.glob(r'**/*.jpg')) + \
                list(image_dir.glob(r'**/*.jpeg')) + \
                list(image_dir.glob(r'**/*.png')) + \
                list(image_dir.glob(r'**/*.JPG')) + \
                list(image_dir.glob(r'**/*.PNG'))

    labels = [os.path.basename(os.path.dirname(p)) for p in filepaths]

    filepaths_series = pd.Series(filepaths, name='Filepath').astype(str)
    labels_series = pd.Series(labels, name='Label')

    return pd.concat([filepaths_series, labels_series], axis=1)

# Deffine DataFrame for Training & Test images
train_df = convert_path_to_df(train_dir)
test_df = convert_path_to_df(test_dir)

print("\n--- DataFrame for Training data (First 5th Rows) ---")
print(train_df.head())
print(f"\nTotal number of training data: {len(train_df)} images")
print(f"Total number of test data: {len(test_df)} images")

"""**6: Check for corrupted images**

Search for corrupted images within the entire dataset. This is to prevent errors caused by image corruption.
"""

print("\n--- Starting corrupted image check ---")
corrupted_images = []
counter = 0
# Using a for loop, list the files from a list of images that could not be opened (or recognized).
for filepath in train_df['Filepath']:
    try:
        img = PIL.Image.open(filepath)
    except PIL.UnidentifiedImageError:
        print(f"Possible corrupted file: {filepath}")
        counter += 1
        corrupted_images.append(filepath)

print("--- Finished corrupted image check ---")
print(f" {counter} corrupted images are found.")

"""**7: Visualize the number of samples per class in the training data (distribution)**

The class distribution of the training data has a direct impact on model training. As such, we visualize the data distribution to precisely assess and confirm the issue of class imbalance—that is, which classes the model will be exposed to often and which classes it will be exposed to rarely during the learning process.
"""

print("\n--- Visualizing class distribution in training data ---")
label_counts = train_df['Label'].value_counts()

plt.figure(figsize=(12, 7))
sns.barplot(x=label_counts.index, y=label_counts.values, palette='viridis')
plt.title('Distribution of Labels in Training Dataset', fontsize=16)
plt.xlabel('Animal Class', fontsize=14)
plt.ylabel('Count', fontsize=14)
plt.xticks(rotation=45)
plt.show()

"""**8: Display random images from the training data**

Sixteen images are randomly sampled from the 10 animal classes within the training dataset and shown with their corresponding class labels. This serves as an initial verification of the data being utilized.
"""

random_index = np.random.randint(0, len(train_df), 16)

# Select 16 random indices from train_df & Create a 4x4 grid (plotting area)
fig, axes = plt.subplots(nrows=4, ncols=4, figsize=(10, 10),
                        subplot_kw={'xticks': [], 'yticks': []})

# Read and display the image & Get the correct label
for i, ax in enumerate(axes.flat):
    ax.imshow(plt.imread(train_df.Filepath[random_index[i]]))
    ax.set_title(train_df.Label[random_index[i]])

plt.tight_layout()
plt.show()

"""**9: Error Level Analysis**

The purpose of this code is to visualize the difference (error level) when a single image is saved with different JPEG compression quality settings, a technique known as Error Level Analysis (ELA). This is used to detect whether an image has been manipulated or edited.
"""

# ELA (Error Level Analysis) function
"""
The original image is loaded, re-compressed as a JPEG, and compared to the original image.
If the image hasn't been tampered with, the difference will be minimal because the entire image is uniformly compressed.
If only a portion has been altered, the error (or discrepancy) will appear significantly larger only in that area.
"""
def compute_ela_pil(path, quality):
    original_image = Image.open(path).convert('RGB')
    buffer = io.BytesIO()
    original_image.save(buffer, format='JPEG', quality=quality)
    buffer.seek(0)
    resaved_image = Image.open(buffer)
    ela_image = ImageChops.difference(original_image, resaved_image)
    extrema = ela_image.getextrema()
    max_diff = max([ex[1] for ex in extrema])

    if max_diff == 0:
        max_diff = 1

    scale = 255.0 / max_diff
    ela_image = ImageEnhance.Brightness(ela_image).enhance(scale)

    return np.array(ela_image)


# --- Select a random image ---
sub_dirs = [d for d in os.listdir(train_dir) if os.path.isdir(os.path.join(train_dir, d))]
random_sub_dir = random.choice(sub_dirs)

random_sub_dir = random.choice(sub_dirs)
path_to_sub_dir = os.path.join(train_dir, random_sub_dir)

image_files = [f for f in os.listdir(path_to_sub_dir) if os.path.isfile(os.path.join(path_to_sub_dir, f))]

random_image_name = random.choice(image_files)
p = os.path.join(path_to_sub_dir, random_image_name)

print(f"Randomly selected image: {p}")

# --- Main plotting process ---
"""
A figure is set up to display the 3*3 grid of images, and each image is then displayed.
By viewing this plot, you can visually confirm if there are any unnatural areas in the images.
"""
orig = cv2.imread(p)
orig = cv2.cvtColor(orig, cv2.COLOR_BGR2RGB) / 255.0
init_val = 100
columns = 3
rows = 3
fig=plt.figure(figsize=(15, 10))

for i in range(1, columns*rows +1):
    quality=init_val - (i-1) * 8

    # Display the original image in the first cell and ELA images in the remaining cells
    if i == 1:
        img = orig.copy()
        title = 'Original'
    else:
        img = compute_ela_pil(path=p, quality=quality)
        title = f'q: {quality}'

    ax = fig.add_subplot(rows, columns, i)
    ax.title.set_text(title)
    plt.imshow(img)
    plt.axis('off')

plt.tight_layout()
plt.show()

"""**10: Visualization of Data augmentation**

These code generate augmented images—with added rotation, scaling, and flipping—from a single original image. This allows the model to learn from diverse image patterns, which improves its robustness to positional shifts and angle variations, thereby increasing its prediction accuracy (generalization performance) on unseen data. We use random images to data augment them using the ImageDataGenerator.
"""

# --- Define data augmentatio ---
data_gen = ImageDataGenerator(
    rotation_range=20, # Randomly rotate images in the range (degrees, 0 to 20)
    width_shift_range=0.1, # Randomly shift images horizontally (max 10%)
    height_shift_range=0.1, # Randomly shift images vertically (max 10%)
    shear_range=0.1, # Apply shear transformation
    zoom_range=0.1, # Randomly zoom image (in/out), Max10%
    horizontal_flip=True, # Randomly flip images horizontally
    fill_mode='nearest', # Strategy for filling in newly created pixels
)

# Select a random image for visualization

random_image_path = random.choice(train_df['Filepath'])

img = cv2.imread(random_image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # Convert the color order from BGR to RGB, which Matplotlib uses for display.

img_array = img[np.newaxis, :]

# Apply data augmentation and visualize
columns = 4
rows = 2
fig = plt.figure(figsize=(15, 8))
fig.suptitle(f'Data Augmentation Examples for: {os.path.basename(random_image_path)}', fontsize=16)

# Display the original image first, and augmented images afterward
ax = fig.add_subplot(rows, columns, 1)
ax.title.set_text('Original')
plt.imshow(img)
plt.axis('off')

i = 1
for batch in data_gen.flow(img_array, batch_size=1):
    aug_img = batch[0].astype('uint8')

    ax = fig.add_subplot(rows, columns, i + 1)
    plt.imshow(aug_img)
    plt.axis('off')

    i += 1
    if i > columns * rows - 1:
        break

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

"""**11: Data preparation (Data augmentation & Splitting data for validation)**

To input new images under the exact same conditions as when ResNet50 was used, we normalize the pixel values using specific mean and standard deviation values via 'preprocess_input'. Twenty percent of the training data will be used for validation.
"""

train_generator = ImageDataGenerator(
    # Settings for data augmentation
    rotation_range=20,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    fill_mode='nearest',

    # Set the preprocessing function
    preprocessing_function=preprocess_input,

    # Validation data split
    # Use 20% of the training data for validation
    validation_split=0.2
)

# Generator for Test data
test_generator = ImageDataGenerator(
    preprocessing_function = preprocess_input
)

"""**12: Create a generator to load data(Traingin, validation, test) from the DataFrame**

Specifying class_mode='categorical' automatically converts string labels like "dog" or "cat" into one-hot vectors, such as [1, 0, 0,...] or [0, 1, 0,...], by the ImageDataGenerator. When evaluating the final performance, the model's predictions must correctly align with the true labels. If the test data is shuffled, the order of predictions and the order of the labels will be randomized, making it impossible to calculate the correct accuracy. Therefore, we set shuffle=False during testing.
"""

# --- Training Images ---
# Load data from train_df and apply data augmentation and preprocessing.
# Using `subset='training'` selects the training portion (80%) from the split defined by validation_split.
print("Creating training data generator...")
train_images = train_generator.flow_from_dataframe(
    dataframe=train_df,
    x_col='Filepath',
    y_col='Label',
    target_size=TARGET_SIZE,
    color_mode='rgb',
    class_mode='categorical', # Convert labels to one-hot encoded format
    batch_size=BATCH_SIZE,
    shuffle=True,             # Shuffle training data at each epoch
    seed=42,
    subset='training'
)

# --- Validation Images ---
# The same data augmentation settings as the training data are applied.
# Using `subset='validation'` selects the validation portion (20%).
print("Creating validation data generator...")
val_images = train_generator.flow_from_dataframe(
    dataframe=train_df,
    x_col='Filepath',
    y_col='Label',
    target_size=TARGET_SIZE,
    color_mode='rgb',
    class_mode='categorical',
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=42,
    subset='validation'
)

# --- Test Images ---
# Load data from test_df and apply only preprocessing.
print("Creating test data generator...")
test_images = test_generator.flow_from_dataframe(
    dataframe=test_df,
    x_col='Filepath',
    y_col='Label',
    target_size=TARGET_SIZE,
    color_mode='rgb',
    class_mode='categorical',
    batch_size=BATCH_SIZE,
    shuffle=False     # No shuffle to maintain the original order of test data
)

print("\nClass indices:", train_images.class_indices)

"""**13: Load the ResNet50 base model**

Following code load a ResNet50 model pre-trained on ImageNet. The input image size is (224, 224, 3), and we exclude the fully connected layer (classifier) used for ImageNet while using the weights learned on ImageNet. GlobalAveragePooling is used as the final pooling layer. The convolutional layers of the ImageNet-trained ResNet50 act as an eye to extract universal features (edges, textures, shapes, etc.) from the images. By "freezing" the weights of this part, we allow the learning to focus on the newly added classification layer and prevent the destruction of the knowledge acquired during pre-training.
"""

# Load the ResNet50 model pre-trained on ImageNet
base_model = ResNet50(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet',
    pooling='avg'
)

# --- Freeze the base model weights ---
# Prevent the pre-trained weights from being updated during training.
base_model.trainable = False

"""**14: Setting up Callbacks to Support Training**

- **ModelCheckpoint**: Saves the model weights only when the validation accuracy (val_accuracy) improves. This ensures that the best-performing model during training is preserved.

- **EarlyStopping**: Stops training if the validation loss (val_loss) does not improve for 5 consecutive epochs.This helps prevent overfitting and saves computation time when model performance plateaus. With restore_best_weights=True, it automatically restores the weights from the epoch with the best validation performance.

- **ReduceLROnPlateau**: Reduces the learning rate to 20% of its current value if the validation loss (val_loss) does not improve for 3 epochs.
This allows the model to fine-tune its weights more precisely when learning stagnates.
"""

# This allbacks monitor the training process and automatically make adjustments

# --- ModelCheckpoint ---
checkpoint_path = "animal_classification_resnet50_checkpoint.weights.h5"
checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    save_weights_only=True, # Saves only the learned "weights"
    monitor="val_accuracy", # Use validation accuracy
    save_best_only=True, # Saves the model only for epochs that achieved a new best record
    verbose=1
)

# --- EarlyStopping ---
early_stopping = EarlyStopping(
    monitor="val_loss", # use validation loss
    patience=25, # Stops training if there is no improvement for 25 consecutive epochs
    restore_best_weights=True
)

# --- ReduceLROnPlateau ---
reduce_lr = ReduceLROnPlateau(
    monitor='val_loss', # use validation loss
    factor=0.2, # Multiplies the current learning rate by 0.2
    patience=3, # Lowers the learning rate if there is no improvement for 3 consecutive epochs
    min_lr=1e-6, # Lower bound for the learning rate
    verbose=1
)

"""**15 Build the model (Add a classification head on top of the base model)**

We add fully connected layers on top of the base model, specialized for our 10-class classification task.
Only this part has its weights updated during the initial training phase.
To prevent overfitting, 50% of the neurons are randomly deactivated.
In the output layer, the number of units is set to 10 to correspond to the 10 classes.
The softmax activation function outputs the probability for each of the 10 classes.
Finally, we connect the input of the *base_model* with our created ‘outputs’ to define the complete model.
"""

# Receive the output from the ResNet50.
x = base_model.output

# --- Add a new classifier ---
x = Dense(256, activation='relu', kernel_regularizer=regularizers.l2(0.01))(x)
x = Dropout(0.45)(x) # Dropout

# --- Output layer ---
outputs = Dense(5, activation='softmax')(x) # 5 animal

# --- Combine the model ---
model = Model(inputs=base_model.input, outputs=outputs)

"""**################################**

**16: Model Loading**

**################################**
"""

################################################################################
# --- {{ Model Loading Code }} ---

# Note: Do NOT run the "Create Model" cell when executing this one.
# Load the pre-trained model saved in Google Drive.
model = keras.models.load_model('/content/drive/MyDrive/Deep_Learning_Group_Assignment.keras')

print("Loaded the saved model from Google Drive.")
model.summary()
################################################################################

"""**17: Compile the our AI model**

We set the optimizer, loss function, and evaluation metric for the model.
The *Adam* optimizer is used, and the standard loss function for multi-class classification, *categorical_crossentropy*, is applied.
The accuracy metric is monitored to evaluate the model’s performance.
"""

# Compile the model
model.compile(
    optimizer=Adam(learning_rate=0.00001), # Optimizer "Adom"
    loss='categorical_crossentropy', # categorical_crossentropy
    metrics=['accuracy']
)

"""**18: Output the model summary**

--------------------------------------------------------------------------------

**Total params: 24,113,541 (91.99 MB)**

**Trainable params: 525,829 (2.01 MB)**

**Non-trainable params: 23,587,712 (89.98 MB)**

--------------------------------------------------------------------------------

Check the architecture and number of parameters of the constructed model.

**input_layer**: This is the input layer where the data first enters.

**conv1_conv (Conv2D)**: This is a convolutional layer, which is the most important part for extracting features like edges and patterns from the image.

**conv1_bn (BatchNormalization)**: This is a layer to stabilize the learning process.

**conv1_relu (Activation)**: This is an activation function that gives the model expressive power.

**Output Shape**: This indicates the shape (dimensions) of the data after passing through each layer.

**(None, 224, 224, 3)**: This means that image data with a variable batch size (None), a height of 224px, a width of 224px, and 3 channels (RGB color) is input.
After passing through conv1_conv, the data is transformed to (None, 112, 112, 64). This indicates that the image size has been halved and 64 different features have been extracted.

**Param #**: This is the number of learnable parameters (weights and biases) contained in that layer. The model becomes smarter by adjusting this vast number of parameters using the training data.

**Connected to**: This shows which layer each layer is connected to, representing the flow of data.

"""

print("--- Model architecture ---")
model.summary()

"""**19: Model Training**"""

# Start training using the prepared data with the `fit` method.
print("\n--- Starting model training ---")
###
EPOCHS = 100 # The number of epochs
###

history = model.fit(
    train_images,
    epochs=EPOCHS,
    steps_per_epoch=len(train_images),
    validation_data=val_images,
    validation_steps=len(val_images),
    callbacks=[
        early_stopping,
        create_tensorboard_callback("training_logs",
                                    "resnet50_animal_classification"),
        checkpoint_callback,
        reduce_lr
    ]
)
print("--- Model training completed ---")

"""**################################**

**20: Save the entire trained model**

**################################**
"""

################################################################################

model.save('/content/drive/MyDrive/Deep_Learning_Group_Assignment.keras')
print("The entire model has been saved to Google Drive.")

################################################################################

"""**21: Final Evaluation with Test Data**

*model.evaluate* is used to calculate the loss and accuracy across the entire test dataset in a single operation. The evaluation metrics displayed here represent the model's final performance score.
"""

# Evaluate the trained model using unseen test data
# Display the final performance score of the model

print("--- Final evaluation on test data ---")
results = model.evaluate(test_images, verbose=0)

print(f"    Test Loss: {results[0]:.5f}")
print(f"Test Accuracy: {results[1] * 100:.2f}%")

"""**21: Visualization of Learning Curves**

We use the loss, accuracy, val_loss, and val_accuracy recorded in history.
**'history'** for each epoch to plot the learning curves. This allows for a visual diagnosis of whether overfitting or underfitting has occurred.
"""

# Retrieve training history data from the 'history' object.
accuracy = history.history['accuracy']
val_accuracy = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(len(accuracy))

# --- Plot two graphs side by side ---
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Plot the changes in Accuracy
ax1.plot(epochs, accuracy, 'r-', label='Training accuracy')
ax1.plot(epochs, val_accuracy, 'b-', label='Validation accuracy')
ax1.set_title('Training and Validation Accuracy')
ax1.set_xlabel('Epochs')
ax1.set_ylabel('Accuracy')
ax1.legend()

# Plot the changes in Loss
ax2.plot(epochs, loss, 'r-', label='Training loss')
ax2.plot(epochs, val_loss, 'b-', label='Validation loss')
ax2.set_title('Training and Validation Loss')
ax2.set_xlabel('Epochs')
ax2.set_ylabel('Loss')
ax2.legend()

fig.suptitle('Learning Curves', fontsize=16)
plt.show()

"""**22: Check Prediction Results**

Following codes perform predictions on the entire test dataset and retrieve the ground truth labels for the test data, and then display the comparison between the predictions and the ground truth.
"""

# Perform prediction on the entire test dataset
pred_probs = model.predict(test_images)
pred_indices = np.argmax(pred_probs, axis=1)

labels = {v: k for k, v in train_images.class_indices.items()}
pred_labels = [labels[k] for k in pred_indices]

# Get the true labels as well
true_indices = test_images.classes
true_labels = [labels[k] for k in true_indices]

# Compare and display predictions and true labels
print("\n--- Comparison of the first 10 prediction results and true labels ---")
for i in range(10):
    print(f"Image {i+1}: Prediction -> {pred_labels[i]:<12} | True Label -> {true_labels[i]}")

"""**23: Visual Review of Prediction Results**

We select 15 random indices from the **test_df** and display three items—the image, the predicted label, and the truth label—in a 3*5 grid (plotting area).
"""

# Select 15 random indices from test_df
random_index = np.random.randint(0, len(test_df), 15)

# Create a 3x5 grid (figure) for plotting
fig, axes = plt.subplots(nrows=3, ncols=5, figsize=(20, 12),
                        subplot_kw={'xticks': [], 'yticks': []})

# Loop through the 15 images
for i, ax in enumerate(axes.flat):

    idx = random_index[i]
    # Read and display the image
    ax.imshow(plt.imread(test_df['Filepath'].iloc[idx]))
    # Get the true and predicted labels
    true_label = true_labels[idx]
    pred_label = pred_labels[idx]

    if true_label == pred_label:
        color = "green"
    else:
        color = "red"

    # Display "True" and "Predicted" labels as the title
    ax.set_title(f"True: {true_label}\nPredicted: {pred_label}", color=color)

plt.tight_layout()
plt.show()

"""**24: Detailed Performance Evaluation with a Classification Report**

This helps to understand which classes the model is good at and which ones it struggles with. Since there might be cases where the model is proficient at predicting 'cat' but poor at predicting 'squirrel', Accuracy alone cannot fully evaluate the model's performance. Therefore, we use Precision, Recall, and F1-score. We display a table formatted as a DataFrame.

**Precision**: The proportion of all instances predicted as 'A' that were truly 'A'. It indicates the model's avoidance of false positives.

**Recall**: The proportion of all instances that were truly 'A' that the model correctly predicted as 'A'. It indicates the model's avoidance of false negatives (or misses).

**F1-score**: The harmonic mean of Precision and Recall. It is higher when there is a good balance between the two metrics.。
"""

# Calculate Precision, Recall, and F1-score for each class.
print("--- Classification Report ---")
print(classification_report(true_labels, pred_labels))


# Convert the report to a DataFrame for better readability
report = classification_report(true_labels, pred_labels, output_dict=True)
df_report = pd.DataFrame(report).transpose()

print("\n--- Report in DataFrame Format ---")
display(df_report)

"""**25: Confusion Matrix**

Visualize which classes the model tends to confuse with others.

Following code section displays a 'Confusion Matrix' which lists which classes the model tends to mistake for others. For instance, if there is a large number in the 'cat' column within the 'dog' row, it indicates that the model frequently misclassifies dogs as cats.
"""

print("--- Confusion Matrix ---")
make_confusion_matrix(y_true=true_labels,
                      y_pred=pred_labels,
                      classes=list(train_images.class_indices.keys()),
                      figsize=(12, 12),
                      text_size=8)
plt.show()

"""**26: Grad-CAM**

Grad-CAM is used to visualize the regions of the image the model focused on when making its class prediction. If the animal part of the image is highlighted in red when correctly classifying the image, it suggests the model is attending to the expected features. Conversely, if the background elements like trees or the ground are highlighted for classification, it indicates that the model has not learned correctly.
"""

# Visualizing the basis for decisions with Grad-CAM
def generate_gradcam_overlay(img_path, model, last_conv_layer_name, pred_index=None):

    # Load and preprocess the image
    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = preprocess_input(img_array)

    # Build a model to compute gradients
    grad_model = tf.keras.models.Model(
        [model.inputs], [model.get_layer(last_conv_layer_name).output, model.output]
    )

    # Record the gradients
    with tf.GradientTape() as tape:
        last_conv_layer_output, preds = grad_model(img_array)
        if pred_index is None:
            pred_index = tf.argmax(preds[0])
        class_channel = preds[:, pred_index]

    # Calculate and pool the gradients
    grads = tape.gradient(class_channel, last_conv_layer_output)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    # Generate the heatmap
    last_conv_layer_output = last_conv_layer_output[0]
    heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)
    heatmap = heatmap.numpy()

    # Overlay the heatmap on the original image
    img = cv2.imread(img_path)
    img = cv2.resize(img, (224, 224))
    heatmap = cv2.resize(heatmap, (img.shape[1], img.shape[0]))
    heatmap = np.uint8(255 * heatmap)
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

    superimposed_img = heatmap * 0.4 + img
    superimposed_img = np.clip(superimposed_img, 0, 255).astype(np.uint8)
    superimposed_img = cv2.cvtColor(superimposed_img, cv2.COLOR_BGR2RGB)

    return superimposed_img


# Execute and visualize Grad-CAM
# Name of the last convolutional layer in ResNet50
last_conv_layer_name = "conv5_block3_out"

# Use the same random indices from the previous step
random_index = np.random.randint(0, len(test_df), 15)

fig, axes = plt.subplots(nrows=3, ncols=5, figsize=(20, 12),
                        subplot_kw={'xticks': [], 'yticks': []})
fig.suptitle("Grad-CAM: Where the Model Looks", fontsize=20)

for i, ax in enumerate(axes.flat):
    idx = random_index[i]
    img_path = test_df.Filepath.iloc[idx]

    # Generate the Grad-CAM image
    overlay_img = generate_gradcam_overlay(img_path, model, last_conv_layer_name)

    # Display the image
    ax.imshow(overlay_img)

    # Set the title
    true_label = true_labels[idx]
    pred_label = pred_labels[idx]
    color = "green" if true_label == pred_label else "red"
    ax.set_title(f"True: {true_label}\nPredicted: {pred_label}", color=color)

plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

"""**27: Prediction and Visualization**

Visualization of Prediction Probabilities for a Test Image Pick up one random image from the test dataset, display the image on the left, and a bar graph of the "probability for each of the 5 classes (Softmax distribution)" predicted by this model on the right.
"""

try:
    from tensorflow.keras.applications.resnet50 import preprocess_input
except ImportError:
    print("Error: preprocess_input not found. Please import it.")


def load_and_prep_image(filename, img_shape=224):
  """
  Reads in an image from filename, turns it into a tensor and reshapes into
  (img_shape, img_shape, 3).
  """
  try:
    img = tf.io.read_file(filename)
    img = tf.image.decode_jpeg(img, channels=3) # Always read with 3 channels
    img = tf.image.resize(img, [img_shape, img_shape])
    return img
  except Exception as e:
    print(f"Error loading image {filename}: {e}")
    return None


# 1. Get the list of class names
# Create a list of class names for the bar graph labels
class_names = list(train_images.class_indices.keys())
print(f"Class names: {class_names}")

# 2. Select a random image from the test data
# Select one random row (image) from test_df (DataFrame)
random_index = random.randint(0, len(test_df) - 1)
image_path = test_df.iloc[random_index]['Filepath']
true_label = test_df.iloc[random_index]['Label']

print(f"Randomly selected image: {image_path}")
print(f"True label: {true_label}")

# 3. Load and Preprocess the image
# a) Original image for visualization (0-255)
original_img = load_and_prep_image(image_path)
# b) Preprocessed image for model prediction
preprocessed_img = preprocess_input(original_img)

if original_img is not None:
    # 4. Perform prediction using the model
    # Add batch dimension to make the shape (1, 224, 224, 3)
    pred_probs = model.predict(tf.expand_dims(preprocessed_img, axis=0))

    pred_probs = pred_probs[0]

    # Get the index of the class with the highest probability
    pred_index = np.argmax(pred_probs)
    pred_label = class_names[pred_index] # Get the class name from the index

    # 5. Visualization (Image and Softmax Probability Distribution Bar Graph)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # --- Right Side: Probability Distribution Bar Graph ---
    #
    # Horizontal bar graph (barh) makes class names easier to read
    ax1.imshow(original_img / 255.0)
    ax1.set_title(f"True: {true_label}\nPredicted: {pred_label}")
    ax1.axis('off')

    # --- Right Side: Probability Distribution Bar Graph ---
    #
    # Horizontal bar graph
    ax2.barh(class_names, pred_probs)
    ax2.set_title("Softmax Probability Distribution")
    ax2.set_xlabel("Probability")
    ax2.set_xlim(0, 1) # Probability range is 0 to 1

    # Change the color of the name for the predicted class
    ax2.get_yticklabels()[pred_index].set_color("red")

    plt.tight_layout()
    plt.show()